"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var HashSet_1 = require("./HashSet");
var HashSet_2 = require("./HashSet");
var hsh = new HashSet_1.HashSett();
hsh.add(12);
hsh.add(2);
hsh.add(12);
hsh.add(17);
hsh.add(2);
hsh.add(0);
var hset = new HashSet_2.HashSet();
hset.add("Рома");
hset.add("Илья");
hset.add("Настя");
hset.add("Никита");
hset.add("Никита");
hset.add("Катя");
hset.add("Гоша");
hset.add("Вася");
hset.add("Лев");
hset.add("Ярик");
hset.add("Дима");
hset.add("Оксана");
hset.add(134);
hset.add(64);
console.log(hset);
console.log("");
console.log(hset.getBucket(0));
console.log(hset.getBucket(1));
console.log(hset.getBucket(2));
console.log(hset.getBucket(3));
console.log(hset.getBucket(4));
console.log(hset.getBucket(5));
console.log(hset.getBucket(6));
console.log(hset.getBucket(7));
console.log(hset.getBucket(8));
console.log(hset.getBucket(9));
console.log(hset.getBucket(10));
console.log(hset.getBucket(11));
console.log(hset.getBucket(12));
console.log(hset.getBucket(13));
console.log(hset.getBucket(14));
console.log(hset.getBucket(15));
console.log(hset.getBucket(16));
console.log(hset.getBucket(17));
console.log(hset.getBucket(18));
console.log(hset.getBucket(19));
// console.log(hset.getBucket();
// let hset = new HashSet();
// hset.add(23);
// console.log(hset);
