"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Linkedlist_1 = require("./Linkedlist");
var list = new Linkedlist_1.SingleLinkedList();
list.add(13);
list.add(15);
list.add(18);
list.add(120);
var el1 = list.getHead();
var el2 = el1.getNext();
var el3 = el2 === null || el2 === void 0 ? void 0 : el2.getNext();
var el4 = el3 === null || el3 === void 0 ? void 0 : el3.getNext();
console.log(el1 === null || el1 === void 0 ? void 0 : el1.getValue());
console.log(el2 === null || el2 === void 0 ? void 0 : el2.getValue());
console.log(el3 === null || el3 === void 0 ? void 0 : el3.getValue());
console.log(el4 === null || el4 === void 0 ? void 0 : el4.getValue());
console.log(el1);
console.log(el2);
console.log(el3);
console.log(el4);
